version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME --build-arg ETSY_API_KEY=$ETSY_API_KEY --build-arg ETSY_API_SECRET=$ETSY_API_SECRET --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE --build-arg AIRBRAKE_PROJECT_ID=$AIRBRAKE_PROJECT_ID --build-arg AIRBRAKE_PROJECT_KEY=$AIRBRAKE_PROJECT_KEY --build-arg RACK_ENV=$RACK_ENV .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Testing docker image
      - docker run $IMAGE_REPO_NAME:$IMAGE_TAG bundle exec rake
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG